insert into pets (pet_id, name, owner_id, age, gender, color, type) values (1,'Mr. Meowshovitz',1,4,'M','black','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (2,'Frank',2,9,'M','orange','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (3,'Ebony',3,1,'F','black','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (4,'Cat',4,2,'M','orange','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (5,'Ugly Face',5,6,'M','multi','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (6,'Fannie',6,2,'F','gray','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (7,'Stella',7,4,'F','gray','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (8,'Ricky',8,7,'M','multi','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (9,'Iggy Pop',9,11,'M','multi','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (10,'TomTom',10,2,'M','black','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (11,'Tim',11,9,'M','blue','cat');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (12,'JerBear',12,9,'M','brown','dog');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (13,'Annie',13,3,'F','white','dog');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (14,'Ghost',14,5,'M','white','dog');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (15,'Reg',15,7,'M','black','dog');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (16,'Honey',16,2,'F','brown','dog');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (17,'Spot',17,1,'M','multi','dog');
insert into pets (pet_id, name, owner_id, age, gender, color, type) values (18,'Sombrita',18,6,'F','black','dog');